version: '3'
 
services:
  frontend:
    build:
      context: .
      dockerfile: devops/front.dockerfile
    ports: 
      - 4000:80
    links:
      - backend-pne
  backend-pne:
    build:
      context: .
      dockerfile: devops/dotnet.dockerfile
    ports:
      - "8080:8080"
    links:
      - db-postgres
    environment: 
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db-postgres:
    #network_mode: host # descomentar para acessar via localhost com dbeaver
    build:
      context: .
      dockerfile: devops/postgres.dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=GMT

